### ISSUE TITLE
[Question] is the 'BadgeVault |' in the badge name necessary?

### ISSUE THREAD

**Issue by XaaRii** [domi-btnr/Vencord-Plugins#3]
I just switched from Replugged to Vencord and I noticed that there is now a sort of prefix 'BadgeVault | ${name}'.
On replugged it was only the name, without this prefix.
I fixed it for myself locally, i just wondered what's the reason behind is... and also, I would rather stay unmodified in case of an update.

Hope you don't mind me asking.

**Comment by domi-btnr** [comment]
I added it, so people know it's from BadgeVault. But ig can make a Setting for it to disable Prefixes

**Comment by XaaRii** [comment]
That sounds great! Thank you!

**Comment by domi-btnr** [comment]
Added in https://github.com/HypedDomi/Vencord-Plugins/commit/6113e87798c7e47d9d8374471cfc0e778cc1cde0
