### ISSUE TITLE
GlobalBadges broke smh

### ISSUE THREAD

**Issue by invisyarcticfox** [domi-btnr/Vencord-Plugins#7]
i cant read any of this so idk what it means buuuttt just letting you know :)
![image](https://github.com/user-attachments/assets/d10ccdce-9f14-412f-947d-a6ec7dd5af53)

**Comment by domi-btnr** [comment]
I fixed this and moved the Plugin to https://github.com/Domis-Vencord-Plugins/GlobalBadges to follow the new guidelines from Vencord for 3rd Party Plugins
